#!/bin/bash

# dusize - Ordered listing of disk usage
# (c) 2006-2012 Alex Malinovich (alex@malinovich.name)
# Released under the GPL v2 or later
# See www.fsf.org for a full copy of the GPL.

if ! DUCMD=`which gdu`; then
	DUCMD=`which du` || exit 1
fi

SORTOPTS="-g"
SEARCHDIR="./"

x=1 # Avoids an error if we get no options at all.
while getopts "r" opt; do
  case "$opt" in
    r) SORTOPTS="-gr";;
  esac
  x=$OPTIND
done
shift $(($x-1))

if [ ! -z "$1" ]; then
	SEARCHDIR="$1"
fi

if [ ! -d "$SEARCHDIR" ]; then
	echo "Invalid directory. Aborting."
	exit 1
fi

"$DUCMD" -xb --max-depth=1 "$SEARCHDIR" | sort $SORTOPTS | gawk '{
	size=$1
	count=0

	while (size > 1023) {
		count++
		size=size/1024
	}

	if (count==4)
		suff="TB"
	else if (count==3)
		suff="GB"
	else if (count==2)
		suff="MB"
	else if (count==1)
		suff="KB"
	else
		suff="B"

	printf("%6.1f %s\t", size, suff)

	for (i=2; i <= NF; i++)
		printf("%s ", $i)
	print ""
}'
