#!/bin/bash
if [ -z "$1" ]; then
	exit 1
elif [ "$1" == "-c" ]; then
	if [ -z "$2" ] || [ -z "$3" ]; then
		exit 1
	fi
	FLEXFILE="$2"
	FLEXFULL="$3"
	SSH_COMMAND="eyscp $FLEXFILE"
else
	if [ "${1: -1}" == "/" ]; then
		FLEXFULL="${1%?}"
	else
		FLEXFULL="$1"
	fi
	SSH_COMMAND="eyssh -A"
fi

if echo "$FLEXFULL" | grep -q '^ssh://'; then
	FLEXHOST=`echo "$FLEXFULL" | sed -E 's/^ssh\:\/\/[a-zA-Z0-9_-]+\@/root\@/'`
elif echo "$FLEXFULL" | egrep -q '^http://[a-zA-Z0-9_-]+'; then
	FLEXHOST=`echo "$FLEXFULL" | sed 's/^http\:\/\//root\@/' | sed 's/\/$//'`
elif echo "$FLEXFULL" | egrep -q '^[0-9]{1,3}\.[0-9]{1,3}.[0-9]{1,3}\.[0-9]{1,3}$' || echo "$FLEXFULL" | grep -q '^.*\.amazonaws\.com$'; then
	FLEXHOST="root@$FLEXFULL"
fi

if [ "$FLEXFULL" == "$FLEXHOST" ] || [ -z "$FLEXHOST" ]; then
	echo -e "FLEXFULL=\"$FLEXFULL\"\nFLEXHOST=\"$FLEXHOST\"" >&2
	echo "Name mangling failed. Aborting."
	exit 1
else
	if grep -q "${FLEXHOST#root@}" ~/.ssh/ey.known_hosts; then
		ssh-keygen -R "${FLEXHOST#root@}" -f ~/.ssh/ey.known_hosts
	fi
	$SSH_COMMAND "$FLEXHOST" 
fi
