#!/bin/bash
if [ -z "$1" ]; then
	exit 1
elif [ "$1" == "-c" ]; then
	if [ -z "$2" ] || [ -z "$3" ]; then
		exit 1
	fi
	FLEXFILE="$2"
	FLEXFULL="$3"
	SSH_COMMAND="eyscp $FLEXFILE"
else
	FLEXFULL="$1"
	SSH_COMMAND="eyssh"
fi

if echo "$FLEXFULL" | grep -q '^ssh://'; then
	FLEXHOST=`echo "$FLEXFULL" | sed -E 's/^ssh\:\/\/[a-zA-Z0-9_-]+\@/root\@/'`
elif echo "$FLEXFULL" | egrep -q '^http://[a-zA-Z0-9_-]+'; then
	FLEXHOST=`echo "$FLEXFULL" | sed 's/^http\:\/\//root\@/' | sed 's/\/$//'`
fi

if [ "$FLEXFULL" == "$FLEXHOST" ]; then
	echo "Name mangling failed. Aborting."
	exit 1
else
	if grep -q "${FLEXHOST#root@}" ~/.ssh/ey.known_hosts; then
		ssh-keygen -R "${FLEXHOST#root@}" -f ~/.ssh/ey.known_hosts
	fi
	$SSH_COMMAND "$FLEXHOST" 
fi
