#!/bin/bash

errormsg="Must supply hostname to scan for. (e.g. nsscan planetargon.com)"

if [ -z $1 ]; then
	echo "$errormsg"
	exit 1
fi

while [ ! -z $1 ]; do
	case "$1" in
		"-h")
			echo "`basename $0` [-x|-d] <name|ip>"
			exit 1
			;;
		"-d")
			debug=true
			;;
		"-x")
			options="-x"
			;;
		*)
			if [ ${1:0:1} == "-" ]; then
				echo "Invalid option \"$1\", aborting."
				exit 1
			fi
			query="$query $1"
			if [ $debug ]; then
				echo "query = $query"
				#echo "\$@ = $@"
			fi
			;;
	esac
	shift
done

if [ -z "$query" ]; then
	echo "$errormsg"
	exit 1
fi

for i in 0 1 2 3; do
	ns=ns$i.planetargon.com
	cmdline="dig @$ns $options $query +short"
	if [ $debug ]; then
		echo "executing: \"$cmdline\""
	fi
	answer="`$cmdline`"
	if [ -z "$answer" ]; then
		answer="no response"
	fi
	echo "$ns: $answer"
	answer=""
done
