#!/bin/bash
if [ -z "$1" ]; then
	echo "Must specify ticket ID"
	exit 1;
fi
echo -n "Fetching requestor... "
REQUESTOR=`rt show ticket/$1 |grep Requestors | cut -f2 -d" "`
if [ ! -z "$REQUESTOR" ]; then
	echo "done."
else
	echo "failed."
	exit 1
fi
echo -n "Removing requestor ($REQUESTOR)... "
if rt edit ticket/$1 del requestors="$REQUESTOR" &>/dev/null; then
	echo "done."
else
	echo "failed."
	exit 1
fi
echo -n "Resolving ticket... "
if rt edit ticket/$1 set status='resolved' &> /dev/null; then
	echo "done."
else
	echo "failed."
	exit 1
fi
echo -n "Re-adding requestor ($REQUESTOR)... "
if rt edit ticket/$1 add requestors="$REQUESTOR" &> /dev/null; then
	echo "done."
else
	echo "failed."
	exit 1
fi
