#!/bin/bash
if [ -z "$1" ]; then
	echo "Must supply server name to show. Aborting."
	exit 1
fi
server="$1"
# ns0 = positron.planetargon.com = 198.145.115.2
# ns1 = proton.planetargon.com = 198.145.115.3
# ns2 = ion.planetargon.com = 198.145.115.4
# ns3 = xenon.planetargon.com = 198.145.115.18
# ns4 = positron.planetargon.com = 198.145.115.2
# ns5 = positron.planetargon.com = 198.145.115.5
# nil = helium.planetargon.com = 198.145.115.100
# nil = hosting.planetargon.com = 64.34.173.156

if [ ! -z ${server} ] && grep -q ${server} $0; then
	grep ${server} $0 | cut -f2- -d" "
else
	echo "\"$1\" not found"
fi
